server:
  port: 9090

spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/Test?serverTimezone=GMT%2b8
      username: root
      password: 200816
mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml文件
#  configuration:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


files:
  upload:
    path: E:/workplace/SpringBoot/files/